### ISSUE TITLE
Improve sharing of configurations

### ISSUE THREAD

**Issue by doki-nordic** [doki-nordic/my-dockers#2]
* Allow configuration assigned to docker file, e.g. `./example.yaml` will be assigned to `./example.Dockerfile`.
  * Configuration will be merged, options from main config file will override docker config.
* Allow parameters in configuration, e.g. docker config has `mem_limit: $$${MEM_LIMIT}` and parameter `params.MEM_LIMIT` with default value `"4g"`.\
  * It can be done using jinja
  * The parameters will be available in configuration, pre/post-build scripts, and dockerfile
  * Parameters can be done using `prompt` (maybe renamed to `input`), e.g. in dockerfile config:
    ```yaml
    prompt:
      MEM_LIMIT: Memory limit  # Create parameter
    set:
      MEM_LIMIT: 4g  # Set default value
    ```
    In global config:
    ```yaml
    set:
      MEM_LIMIT: 1g  # Override default value
    ```

**Comment by doki-nordic** [comment]
Or, different approach:
* put both sources and ncs/zephyr dockerfiles into one repository
* each user has newest repository version
* each user has its own configuration file that only loads commands from common repository, e.g.
  ```yaml
  ncs:
    load: my-dockers/config.yaml:ncs
    share: /home/doki/work
  ncs-low-mem:
    load: $this:ncs
    options:
      mem_limit: 2g
  ```
* Each command has a description
* `my-dockers` command shows also commands from base config file that are not used in user config.
* User configs are in repository root directory and they are in `.gitignore`
* Main user config file is created automatically if not exists.

**Comment by doki-nordic** [comment]
Also automatic version control support would be nice: e.g.
```yaml
ncs-2.8:
  load:
    repo: https://github.com/doki-nordic/my-dockers/
    branch: sdk-v2.8
    file: config.yaml
    command: ncs
    # Or one-liner: https://github.com/doki-nordic/my-dockers/#config.yaml:ncs@sdk-v2.8
    # Format: repo#path:command@commit
    # repo - optional, local file system without version control by default
    # path - requred
    # command - optional, the same as current by default
    # commit - optional, main/master by default
  share: /home/doki/work
```
If it is reference to repository:
* Clone this repository to dedicated directory
* If repository contains entire `my-dockers` repo, create new `.venv`
* Find repository that contains `my-dockers/config.yaml`. File may not exists, so the directory will be used to find out the repository.
* If we are on correct commit, just use it. Otherwise, continue
* Clone entire repository to temporary directory, e.g. `_temp/sdk-v2.8`. Reuse, if already exists, and fetch all changes from source directory.
* Checkout commit `sdk-v2.8` (with cleanup of entire workspace)
*
